apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ project_admin }}-get-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-namespaces
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ project_admin }}