---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{ application_name }}
  name: {{ buildconfig_name }}
spec:
  resources:
    limits:
      memory: 3Gi
      cpu: 1
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: "{{ application_name }}:latest"
  postCommit: {}
  runPolicy: Serial
  source:
    git:
      uri: "{{ git_url }}"
      ref: "{{ git_ref }}"
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: "{{ application_image }}"
        namespace: "{{ application_image_namespace }}"
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: {{ github_secret }}
      type: GitHub
    - generic:
        secret: {{ generic_secret }}
      type: Generic
    - type: ConfigChange
    - type: ImageChange
