apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ dw_application_service_account }}-view
  namespace: {{ namespace }}
roleRef:
  kind: ClusterRole
  name: view
  namespace: {{ namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ dw_application_service_account }}
    namespace: {{ namespace }}
