apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {{ namespace_amq_streams_operator }}
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {{ namespace_kafka_cluster }}
